//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierCalculator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ubs_ProdEntities : DbContext
    {
        public Ubs_ProdEntities()
            : base("name=Ubs_ProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<p_CountAverageWeeklyBySupplier_Result> p_CountAverageWeeklyBySupplier()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_CountAverageWeeklyBySupplier_Result>("p_CountAverageWeeklyBySupplier");
        }
    }
}
